[package]
name = "cooplan-mongodb"
version = "0.2"
edition = "2021"
license = "MIT"
description = "Cooplan wrapper for MongoDB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# MongoDB
mongodb = "2.3.1"